### PR TITLE
A bit more =)

### PR DESCRIPTION
**Pull request by Vlad-00003**
So, here is what I've added:

1. Brought back unlocking steam items. (This is not something really big, but hey - why don't allow players to have it, as long as we are here?)
2. Added config option to allow players who has used the console to get achievements with it.
3. Now the first time config has been generated it would be well-formatted, insted of 1 line =)
4. This is not something big, but with the [JsonProperty] you can easily setup user-friendly names on the config parametrs.
5. Added exception handler in case of the patch fails. Just to be sure that the game won't crash and the player would have the info to provide for you.

### CODE REVIEW

**Comment by Vlad-00003** [comment]
Now I've also added the config options for the exosuit storage.

**Comment by Vlad-00003** [comment]
@Qwiso, check out the latest fix - for the VendingMachine and CoffeVendingMachine patches.
The one for CoffeVendingmachin.OnMachineUse is not really nessasarry, but as I know it would increse performance a bit - reflection would be called just once insted of each prefix call.
And about the VendingMachine - your way(just adding a postfix to the func) is... kinda not good. Why? Well, basicly the player got 1 coffe each time he pushes the button. No matter how much time has passed since last usage. So - in one second I was able to get ~15 cups of coffe and 1 pack of chips... This is kinda wired.

**Comment by Vlad-00003** [comment]
Wow. All of it?)
But I still don't like the idea of you just ignoring what I'm typing =_=

**Comment by Qwiso** [comment]
@Vlad-00003  Sorry, I do have real work to worry about sometimes. Do you use discord? It's hard for me to manage so many points of contact

**Comment by Vlad-00003** [comment]
@Qwiso, yeah, I understand that. I also don't have much free time, but you have enought time to merge requests.... what does it take to type some text while doing so?)

Yes - I do have a discord - Vlad-00003#4401

**Pull request merged**
